# Generated by Django 5.2.3 on 2025-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("year", models.CharField(max_length=50)),
                ("imdb_id", models.CharField(max_length=100, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("poster", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
